### ISSUE TITLE
Error: must be string, not instance

### ISSUE THREAD

**Issue by standevo** [RedFantom/mtTkinter#7] opened 2018-03-09 09:05 UTC
Hi. I trying to use mtTkinter but got a strange error.

` must be string, not instance`

I think from the screenshot you can see where is the problem.
Thx

![screenshot_1](https://user-images.githubusercontent.com/8398942/37199239-577266f0-2381-11e8-9820-74b90b8288b5.png)

**Comment by RedFantom** [comment] 2018-03-09 09:14
Thank you for providing such a complete traceback, that might help in pinpointing the problem. I do have a few more questions though:
- Do you not have this error when not importing mtTkinter at all?
- Do you import mtTkinter more than once?
- Does this issue occur with the `0.5.0` version of mtTkinter?

mtTkinter only seems to be raising an error exactly like it is supposed to in the last line of the traceback. It could be that mtTkinter is causing the error though, but I need some code to reproduce first, and given how this error was raised in a program that seems very large, reproduction on my side is not possible without an example.

**Comment by standevo** [comment] 2018-03-09 09:22
Thank you for fast answer. I'll give more details.

1. I don't have this error with clean tkinter (without mtTkinter)
2. I do: from mttkinter import mtTkinter as tkinter in every file which i need to use tkinter stuff
3. I don't know about versions. I use the latest one.

Notice:
- This error is raising only in threads.
- I tried also to include mtTkinter only once (in main file) but got the same error
- You can reproduce it simply if you start a new thread with:
`self.x = tkinter.BooleanVar() # (or tkinter.StringVar() etc)`

**Comment by RedFantom** [comment] 2018-03-09 09:40
Thank you. I have been able to reproduce the issue, and as it turns out I made an error in refactoring attributes. The error is fixed in the `bugfix` branch. Once CI is complete, I will merge it into the master branch.

**Comment by standevo** [comment] 2018-03-09 09:43
Thank you.
Prompt, fast, effective.

**Closed as completed** 2018-03-09 09:46 UTC
Labels: bug

**Comment by RedFantom** [comment] 2018-03-09 09:48
Once CI is done again, I will tag a new version and publish to PyPI, so you can easily test the solution. Thank you for letting me know about this issue! If you have any more issues, please don't hesitate to let me know.

**Comment by RedFantom** [comment] 2018-03-09 09:51
`0.6.1` tagged and published.
